stages:
- name: build-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 2048demo-image-test
      pushRemote: true
      registry: index.docker.io
timeout: 60
