stages:
- name: build-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 2048-image-demo
      pushRemote: true
      registry: quay.io/anypm/2048demo
timeout: 60
