stages:
- name: build-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: 2048demox
      pushRemote: true
      registry: quay.io/anypm
- name: deploy-stage
  steps:
  - applyYamlConfig:
      path: ./.rancher-pipeline.yml
timeout: 60
