stages:
- name: build-stage
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: example-2048demo:${CICD_EXECUTION_SEQUENCE}
      registry: quay.io/anypm
- name: deploy-stage
  steps:
  - applyYamlConfig:
      path: ./deployment.yaml
timeout: 60
